spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: file
server:
  port: 15000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6000/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true